import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';
import stylstLogo from '@/assets/stylst-logo.png';

const Terms = () => (
  <div className="min-h-screen bg-background">
    <nav className="flex items-center justify-between px-6 md:px-12 py-6 border-b border-border">
      <Link to="/" className="flex items-center gap-2">
        <img src={stylstLogo} alt="Stylst" className="w-8 h-8 rounded" />
        <span className="font-display text-xl font-bold text-primary">Stylst</span>
      </Link>
      <Link to="/">
        <Button variant="ghost" size="sm"><ArrowLeft className="w-4 h-4 mr-1" /> Back</Button>
      </Link>
    </nav>

    <main className="max-w-3xl mx-auto px-6 py-12 prose prose-neutral dark:prose-invert">
      <h1>Terms of Service</h1>
      <p className="text-muted-foreground">Last updated: July 2, 2026</p>

      <p>These Terms of Service ("Terms") govern your access to and use of the Stylst app and website (the "Service"). By creating an account or using the Service, you agree to these Terms. If you do not agree, please do not use the Service.</p>

      <h2>1. Eligibility</h2>
      <p>You must be at least 16 years old, or the age of digital consent in your country, to use Stylst. By using the Service you confirm that you meet this requirement.</p>

      <h2>2. Your Account</h2>
      <p>You are responsible for the information you provide and for keeping your login credentials secure. You are responsible for all activity that happens under your account. Let us know promptly if you believe your account has been compromised.</p>

      <h2>3. Your Content</h2>
      <p>You keep ownership of the photos and other content you upload ("Your Content"). By uploading, you grant Stylst a limited, non-exclusive licence to store, process, and display Your Content solely to provide the Service to you (for example, cleaning up clothing images, matching outfits, and generating styling suggestions). You confirm that you have the rights to any content you upload and that it does not infringe anyone else's rights.</p>

      <h2>4. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>upload content that is illegal, infringing, abusive, or that you do not have the right to share;</li>
        <li>attempt to reverse engineer, disrupt, overload, or gain unauthorized access to the Service or its systems;</li>
        <li>use the Service to build a competing product or to scrape data at scale;</li>
        <li>misuse the AI features or third-party integrations in a way that violates their terms.</li>
      </ul>

      <h2>5. Third-Party Services</h2>
      <p>If you connect Pinterest or another third-party service, your use of that service is also governed by that provider's own terms and privacy policy. We are not responsible for third-party services and only access what you authorize. See our <Link to="/privacy">Privacy Policy</Link> for how integration data is handled.</p>

      <h2>6. AI-Generated Suggestions</h2>
      <p>Outfit matches, styling suggestions, and any shopping results are generated by AI and provided for inspiration only. They may be inaccurate or incomplete and are not professional styling, retail, or purchasing advice. Any prices, product details, or links shown come from third parties and may change or be unavailable. Always verify details before making a purchase.</p>

      <h2>7. Intellectual Property</h2>
      <p>The Stylst name, logo, app, and underlying software are owned by Stylst and are protected by intellectual property laws. These Terms do not grant you any right to use our branding except as needed to use the Service.</p>

      <h2>8. Service Availability</h2>
      <p>We work to keep the Service running, but we may add, change, suspend, or remove features at any time. The Service is provided on an "as is" and "as available" basis without warranties of any kind, to the fullest extent permitted by law.</p>

      <h2>9. Limitation of Liability</h2>
      <p>To the fullest extent permitted by law, Stylst will not be liable for any indirect, incidental, or consequential damages, or for any loss of data, arising from your use of the Service.</p>

      <h2>10. Termination and Account Deletion</h2>
      <p>You can delete your account at any time in Settings, which permanently removes your data as described in our <Link to="/privacy">Privacy Policy</Link>. We may suspend or terminate access if you breach these Terms or misuse the Service.</p>

      <h2>11. Changes to These Terms</h2>
      <p>We may update these Terms from time to time. If we make material changes, we will notify you by email or through the app. Continuing to use the Service after changes take effect means you accept the updated Terms.</p>

      <h2>12. Governing Law</h2>
      <p>These Terms are governed by the laws of England and Wales, without regard to conflict-of-law rules. Any disputes will be subject to the exclusive jurisdiction of the courts of England and Wales.</p>

      <h2>13. Contact</h2>
      <p>For questions about these Terms, email <a href="mailto:support@stylst.app">support@stylst.app</a>.</p>
    </main>
  </div>
);

export default Terms;
